replicaCount: 1

image:
  repository: hcr.data.here.com/ota_saas/web-events
  tag: latest
  pullPolicy: IfNotPresent

readinessProbe:
  initialDelaySeconds: 5

configMap:
  AUTH_PROTOCOL: oauth.accesstoken
  AUTH_VERIFICATION: local
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  JAVA_OPTS: -XshowSettings:vm -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  LOG_APPENDER: async_json
  REPORT_METRICS: "false"

service:
  type: ClusterIP
  port: 80
  # These can be set when using the LoadBalancer type on a non-local setup:
  # internal: true
  # sslCert: arn:aws:iam::123456787890:server-certificate/cert-name
  # sslPorts: "*"
  # dnsName: web-events.ota.local

secret: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - web-events.ota.local
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 350Mi

prometheus:
  scrape: false

registryPullSecret: docker-registry-key

nodeSelector: {}

tolerations: []

affinity: {}

withAuthPlus: true

pdb:
  enabled: false
  maxUnavailable:
  minAvailable:
