---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: {{ .mysql_docker_image }}
        name: mysql
        envFrom:
        - secretRef:
            name: mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-proot", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        volumeMounts:
        - name: infra-vol
          mountPath: /var/lib/mysql
          subPath: mysql

  volumeClaimTemplates:
  - metadata:
      name: infra-vol
      {{- if .storage_class_name}}
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .storage_class_name }}
      {{- end}}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .mysql_disk }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .mysql_root_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
