---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data:
  ZK_REPLICAS: "1"
  ZK_HEAP_SIZE: "250M"
  ZK_TICK_TIME: "2000"
  ZK_INIT_LIMIT: "10"
  ZK_SYNC_LIMIT: "5"
  ZK_MAX_CLIENT_CNXNS: "60"
  ZK_SNAP_RETAIN_COUNT: "3"
  ZK_PURGE_INTERVAL: "1"
  ZK_LOG_LEVEL: INFO
  ZK_CLIENT_PORT: "2181"
  ZK_SERVER_PORT: "2888"
  ZK_ELECTION_PORT: "3888"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: {{ .zookeeper_docker_image }}
        envFrom:
        - configMapRef:
            name: zookeeper-config
        command: ['sh', '-c', 'zkGenConfig.sh && exec zkServer.sh start-foreground']
        livenessProbe:
          exec:
            command: ["zkOk.sh"]
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: election
        readinessProbe:
          exec:
            command: ["zkOk.sh"]
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: {{ .zookeeper_cpu }}
            memory: {{ .zookeeper_mem }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: zookeeper-claim
          mountPath: /var/lib/zookeeper
          subPath: zookeeper
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .storage_class_name }}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .zookeeper_disk }}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: peer
  - port: 3888
    name: election
  selector:
    app: zookeeper
