replicaCount:
  main: 1
  daemon: 1

image:
  repository: hcr.data.here.com/ota_saas/device-registry
  tag: latest
  pullPolicy: IfNotPresent

lifecycle:
  preStopTimeSec: 25
  terminationGracePeriodSeconds: 30 # 30 sec is used by default

readinessProbe:
  initialDelaySeconds: 5

HorizontalPodAutoscaler:
  averageUtilization: 65
  maxReplicas: 5
  minReplicas: 4

configMap:
  AUTH_PROTOCOL: 'none'
  BIND_HOST: 0.0.0.0
  BIND_PORT: 9001
  DB_MIGRATE: true
  DB_URL: jdbc:mariadb://ota-mariadb:3306/device_registry
  DB_USER: device_registry
  JAVA_OPTS: -XshowSettings:vm -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  LOG_APPENDER: async_json
  REPORT_METRICS: false
  ATS_HTTP_TRACING: "true"
  ZIPKIN_URI: "http://ota-zipkin:9411"

service:
  type: ClusterIP
  port: 80

secret:
  DB_PASSWORD: device_registry

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - device-registry.ota.local
  tls: []

resources:
  requests:
    cpu: 80m
    memory: 300Mi

daemonResources:
  requests:
    cpu: 80m
    memory: 300Mi

registryPullSecrets: docker-registry-key

nodeSelector: {}

tolerations: []

affinity: {}

pdb:
  enabled: false
  maxUnavailable:
  minAvailable:
