---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ota-director.fullname" . }}
  labels:
    app: {{ template "ota-director.name" . }}
    chart: {{ template "ota-director.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.main }}
  selector:
    matchLabels:
      app: {{ template "ota-director.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ota-director.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- if .Values.registryPullSecret }}
      imagePullSecrets:
      - name: {{ .Values.registryPullSecret }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.lifecycle.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "{{ .Values.lifecycle.preStopTimeSec }}"]
          envFrom:
          - configMapRef:
              name: {{ template "ota-director.fullname" . }}
          - secretRef:
              name: {{ template "ota-director.fullname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.configMap.BIND_PORT }}
              name: http
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 30
            httpGet:
              path: "/health"
              port: {{ .Values.configMap.BIND_PORT }}
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: 10
            httpGet:
              path: "/health"
              port: {{ .Values.configMap.BIND_PORT }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
