---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuf-vault-config
data:
  DEFAULT_LEASE_TTL: 30s
  MAX_LEASE_TTL: 30s
  MYSQL_ADDR: {{ .mysql_host }}:3306
  MYSQL_DATABASE: tuf_vault
  MYSQL_DATABASE_TABLE: tuf_vault
  MYSQL_USERNAME: tuf_vault
  REPORT_METRICS: "false"
  VAULT_ADDR: "http://127.0.0.1:8200"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tuf-vault
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-vault
    spec:
      containers:
      - image: {{ .tuf_vault_docker_image }}
        name: tuf-vault
        envFrom:
        - configMapRef:
            name: tuf-vault-config
        - secretRef:
            name: tuf-vault-secret
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8200
        args:
        resources:
          requests:
            cpu: {{ .tuf_vault_cpu }}
            memory: {{ .tuf_vault_mem }}
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            port: 8200
            path: /v1/sys/init
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: v1
kind: Secret
metadata:
  name: tuf-vault-secret
type: Opaque
data:
  MYSQL_PASSWORD: {{ .tuf_vault_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: tuf-vault
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8200
  selector:
    app: tuf-vault
