= Welcome to the OTA Community Edition Docs!
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

This is the automatic start page for version *{page-component-version}* of the OTA Community Edition guide.

The OTA Community Edition guide is one of two documentation components in the new OTA Connect Docs Demo.
The other docs component, aktualizr can be accessed via the component selector menu (aka component drawer) at the bottom of the menu on the left side of the page.

== Page source

This page is sourced from the AsciiDoc file named [.path]_index.adoc_ that is located at [.path]_ota-community-edition/docs/modules/ROOT/pages_.

=== Why is this the home page of the OTA Community Edition guide?

This page is automatically used as the start page of the OTA Community Edition guide because it is stored in the ROOT module and named [.path]_index.adoc_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in the ROOT module of the OTA Community Edition guide*, the xref syntax would be `\xref:index.adoc[]`.

To create a cross reference *to this page from a page in Module One of the OTA Community Edition guide*, the xref syntax would be `\xref:ROOT:index.adoc[]`.

=== Always target the latest version of this page

To create a cross reference *to the latest version of this page from a page in Component A*, the xref syntax would be `\xref:ota-ce::index.adoc[]`.

=== Target a specific version of this page

To create a cross reference *to version 1.0 of this page from a page in Component A*, the xref syntax would be `\xref:1.0@ota-ce::index.adoc[]`.
