---
apiVersion: v1
kind: ConfigMap
metadata:
  name: campaigner-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/campaigner
  DB_USER: campaigner
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: director
  DIRECTOR_PORT: '80'
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .campaigner_java_opts }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafka_host }}:9092
  KAFKA_HOST: {{ .kafka_host }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafka_topic_suffix }}
  MESSAGING_MODE: kafka
  REPORT_METRICS: "false"
  SCHEDULER_BATCH_SIZE: '200'
  SCHEDULER_DELAY: 10 seconds
  SCHEDULER_POLLING_TIMEOUT: 10 seconds
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: campaigner
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: campaigner
    spec:
      containers:
      - image: {{ .campaigner_docker_image }}
        name: campaigner
        envFrom:
        - configMapRef:
            name: campaigner-config
        - secretRef:
            name: campaigner-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        args:
        resources:
          requests:
            cpu: {{ .campaigner_cpu }}
            memory: {{ .campaigner_mem }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: campaigner
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: campaigner.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: campaigner
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: campaigner-secret
type: Opaque
data:
  DB_PASSWORD: {{ .campaigner_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: campaigner
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: campaigner
