---
apiVersion: v1
kind: ConfigMap
metadata:
  name: director-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/director
  DB_USER: director
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .director_java_opts }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafka_host }}:9092
  KAFKA_HOST: {{ .kafka_host }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafka_topic_suffix }}
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TUF_KEYSERVER_HOST: tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: director
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: director
    spec:
      containers:
      - image: {{ .director_docker_image }}
        name: director
        envFrom:
        - configMapRef:
            name: director-config
        - secretRef:
            name: director-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        args:
        resources:
          requests:
            cpu: {{ .director_cpu }}
            memory: {{ .director_mem }}
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: director
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: director.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: director
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: director-secret
type: Opaque
data:
  DB_PASSWORD: {{ .director_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: director
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: director
