---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  gateway.conf: |-
    server {
      error_log  /var/log/nginx/error.log info;
      listen       8443 ssl;
      server_name ota.ce;
      ssl_certificate     /etc/ssl/gateway/server.chain.pem;
      ssl_certificate_key /etc/ssl/gateway/server.key;
      ssl_verify_client on;
      ssl_verify_depth 10;
      ssl_client_certificate /etc/ssl/gateway/ca.crt;

      if ($ssl_client_s_dn ~ "CN=(.*)$") {
        set $deviceUuid $1;
      }
      if ($ssl_client_s_dn !~ "CN=(.*)$") {
        set $deviceUuid $ssl_client_s_dn;
      }
      set $deviceNamespace "default";

      location /treehub/ {
        rewrite ^/treehub/(.*)$ /api/v2/$1 break;
        proxy_set_header x-ats-device-uuid $deviceUuid;
        proxy_set_header x-ats-namespace $deviceNamespace;
        proxy_pass http://treehub;
      }

      location /director/ {
        rewrite ^/director/(.*)$ /api/v1/device/${deviceUuid}/$1 break;
        proxy_set_header x-ats-namespace $deviceNamespace;
        proxy_pass http://director;
      }

      location /repo/ {
        rewrite ^/repo/(.*)$ /api/v1/user_repo/$1 break;
        proxy_set_header x-ats-namespace $deviceNamespace;
        proxy_pass http://repo;
      }

      location /core/system_info {
        rewrite ^/core/(.*)$ /api/v1/mydevice/$deviceUuid/$1 break;
        proxy_set_header x-ats-namespace $deviceNamespace;
        proxy_pass http://device-registry;
      }
      location /core/installed {
        rewrite ^/core/(.*)$ /api/v1/mydevice/$deviceUuid/packages break;
        proxy_set_header x-ats-namespace $deviceNamespace;
        proxy_pass http://device-registry;
      }
    }
  upstreams.conf: |-
    upstream treehub {
      server treehub:80;
    }

    upstream director {
      server director:80;
    }

    upstream repo {
      server tuf-reposerver:80;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: nginx
        image: {{ .nginx_docker_image }}
        command: ["nginx-debug", "-g", "daemon off;"]
        envFrom:
        - secretRef:
            name: gateway-tokens
        ports:
        - containerPort: 80
        - containerPort: 8443
        volumeMounts:
        - name: gateway-config
          mountPath: /etc/nginx/conf.d/
        - name: gateway-tls
          mountPath: /etc/ssl/gateway/
          readOnly: true
      volumes:
      - name: gateway-config
        configMap:
          name: gateway-config
      - name: gateway-tls
        secret:
          secretName: gateway-tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/whitelist-source-range: {{ .ingress_acl_whitelist }}
spec:
  rules:
  - host: gateway.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
  - name: gateway
    port: 8000
    targetPort: 8443
  selector:
    app: gateway
