apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: campaigner
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: campaigner.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: campaigner
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: device-registry
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: device-registry.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: device-registry
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: director
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: director.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: director
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: treehub
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 30m
spec:
  rules:
  - host: treehub.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: treehub
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tuf-keyserver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tuf-keyserver.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: tuf-keyserver
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tuf-reposerver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tuf-reposerver.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: tuf-reposerver
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tuf-vault
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tuf-vault.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: tuf-vault
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-events
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: web-events.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: web-events
          servicePort: 80
