apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ota
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 80
  - host: campaigner.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: campaigner
          servicePort: 80
  - host: device-registry.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: device-registry
          servicePort: 80
  - host: director.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: director
          servicePort: 80
  - host: treehub.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: treehub
          servicePort: 80
  - host: tuf-keyserver.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: tuf-keyserver
          servicePort: 80
  - host: tuf-reposerver.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: tuf-reposerver
          servicePort: 80
  - host: tuf-vault.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: tuf-vault
          servicePort: 80
  - host: web-events.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: web-events
          servicePort: 80
