---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuf-reposerver-config
data:
  AUTH_PROTOCOL: none
  AUTH_VERIFICATION: none
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/tuf_reposerver
  DB_USER: {{ .tuf_reposerver_db_user }}
  JAVA_OPTS: {{ .tuf_reposerver_java_opts }}
  REPORT_METRICS: "false"
  {{- if .tuf_reposerver_local_storage_root}}
  LOCAL_STORAGE_ROOT: {{ .tuf_reposerver_local_storage_root }}
  STORAGE_TYPE: local
  {{- end}}
  TUF_KEYSERVER_HOST: tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_SIZE_LIMIT: "536870912"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuf-reposerver
spec:
  selector:
    matchLabels:
      app: tuf-reposerver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-reposerver
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - name: tuf-reposerver
        image: {{ .tuf_reposerver_docker_image }}
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: tuf-reposerver-config
        - secretRef:
            name: tuf-reposerver-secret
        ports:
        - containerPort: 9001
        resources:
          requests:
            cpu: {{ .tuf_reposerver_cpu }}
            memory: {{ .tuf_reposerver_mem }}
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
---
{{- if .create_ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tuf-reposerver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tuf-reposerver.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: tuf-reposerver
          servicePort: 80
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: tuf-reposerver-secret
type: Opaque
data:
  DB_PASSWORD: {{ .tuf_reposerver_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: tuf-reposerver
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: tuf-reposerver
