---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuf-reposerver-config
data:
  AUTH_PROTOCOL: none
  AUTH_VERIFICATION: none
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/tuf_reposerver
  DB_USER: tuf_reposerver
  JAVA_OPTS: {{ .tuf_reposerver_java_opts }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafka_host }}:9092
  KAFKA_HOST: {{ .kafka_host }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafka_topic_suffix }}
  REPORT_METRICS: "false"
  TUF_KEYSERVER_HOST: tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_AWS_BUCKET_ID: ota-ce-tuf-reposerver
  TUF_REPOSERVER_AWS_REGION: eu-central-1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tuf-reposerver
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-reposerver
    spec:
      containers:
      - image: {{ .tuf_reposerver_docker_image }}
        name: tuf-reposerver
        envFrom:
        - configMapRef:
            name: tuf-reposerver-config
        - secretRef:
            name: tuf-reposerver-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        args:
        resources:
          requests:
            cpu: {{ .tuf_reposerver_cpu }}
            memory: {{ .tuf_reposerver_mem }}
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tuf-reposerver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tuf-reposerver.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: tuf-reposerver
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: tuf-reposerver-secret
type: Opaque
data:
  DB_PASSWORD: {{ .tuf_reposerver_db_password | b64enc }}
  TUF_REPOSERVER_AWS_ACCESS_KEY: {{ .tuf_reposerver_aws_key | b64enc }}
  TUF_REPOSERVER_AWS_SECRET_KEY: {{ .tuf_reposerver_aws_secret | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: tuf-reposerver
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: tuf-reposerver
