---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuf-keyserver-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/tuf_keyserver
  DB_USER: {{ .tuf_keyserver_db_user }}
  JAVA_OPTS: {{ .tuf_keyserver_java_opts }}
  REPORT_METRICS: "false"
{{ if contains .tuf_keyserver_docker_image ":0.3." }}
  TUF_VAULT_HOST: tuf-vault
  TUF_VAULT_PORT: '80'
{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuf-keyserver
spec:
  selector:
    matchLabels:
      app: tuf-keyserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-keyserver
    spec:
{{ if .gke_nodepool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .gke_nodepool }}
{{ end }}
      containers:
      - name: tuf-keyserver
        image: {{ .tuf_keyserver_docker_image }}
        args:
        - "-main"
        - com.advancedtelematic.tuf.keyserver.Boot
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: tuf-keyserver-config
        - secretRef:
            name: tuf-keyserver-secret
{{ if contains .tuf_keyserver_docker_image ":0.3." }}
        - secretRef:
            name: tuf-tokens
{{ else }}
        - secretRef:
            name: tuf-keyserver-encryption
{{ end }}
        ports:
        - containerPort: 9001
        resources:
          requests:
            cpu: {{ .tuf_keyserver_cpu }}
            memory: {{ .tuf_keyserver_mem }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
---
apiVersion: v1
kind: Secret
metadata:
  name: tuf-keyserver-secret
type: Opaque
data:
  DB_PASSWORD: {{ .tuf_keyserver_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: tuf-keyserver
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: tuf-keyserver
