---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_ZOOKEEPER_CONNECT: "{{ .zookeeper_host }}:2181"
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 1
  serviceName: kafka
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: {{ .kafka_docker_image }}
        imagePullPolicy: IfNotPresent
        name: kafka
        envFrom:
        - configMapRef:
            name: kafka-config
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        command:
        - sh
        - -c
        - |
          unset KAFKA_PORT && \
          export KAFKA_ADVERTISED_HOST_NAME=${POD_IP} && \
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && \
          export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
          /etc/confluent/docker/run
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9092
          timeoutSeconds: 5
        ports:
        - containerPort: 9092
        readinessProbe:
          exec:
            command:
            - kafka-topics
            - --zookeeper
            - {{ .zookeeper_host }}:2181
            - --list
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: {{ .kafka_cpu }}
            memory: {{ .kafka_mem }}
        volumeMounts:
        - name: platform-vol
          mountPath: /opt/kafka/data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

  volumeClaimTemplates:
  - metadata:
      name: platform-vol
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
