replicaCount:
  main: 1
  daemon: 1

image:
  repository: hcr.data.here.com/ota_saas/tuf-keyserver
  tag: latest
  pullPolicy: IfNotPresent

lifecycle:
  preStopTimeSec: 25
  terminationGracePeriodSeconds: 30 # 30 sec is used by default

readinessProbe:
  initialDelaySeconds: 5

HorizontalPodAutoscaler:
  averageUtilizationCPU: 65
  maxReplicas: 3
  minReplicas: 2

configMap:
  BIND_PORT: '9001'
  BIND_HOST: '0.0.0.0'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://ota-mariadb:3306/tuf_keyserver
  DB_USER: tuf_keyserver
  JAVA_OPTS: -XshowSettings:vm -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  LOG_APPENDER: async_json
  REPORT_METRICS: "false"
  ATS_HTTP_TRACING: "true"
  ZIPKIN_URI: "http://ota-zipkin:9411"
  AKKA_HTTP_CLIENT_MAX_OPEN_REQUESTS: 2048
  AKKA_HTTP_CLIENT_MAX_CONNECTIONS: 1024
  AKKA_HTTP_MAX_CONNECTIONS: 2048

secret:
  DB_PASSWORD: tuf_keyserver
  DB_ENCRYPTION_PASSWORD: h3pJZd9PvB47lvMcpnp0SS92jNYoB050Ke4dN1wYB4N36w5RjYZfcWj1Pg7Hbths
  DB_ENCRYPTION_SALT: EoKxIawx0Y4=

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - tuf-keyserver.ota.local
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: []

resources:
  requests:
    cpu: 80m
    memory: 300Mi

daemonResources:
  requests:
    cpu: 80m
    memory: 300Mi

pdb:
  enabled: false
  maxUnavailable:
  minAvailable:

registryPullSecret: docker-registry-key
