replicaCount:
  main: 1
  daemon: 1

image:
  repository: hcr.data.here.com/ota_saas/campaigner
  tag: latest
  pullPolicy: IfNotPresent

lifecycle:
  preStopTimeSec: 25
  terminationGracePeriodSeconds: 30 # 30 sec is used by default

readinessProbe:
  initialDelaySeconds: 5

configMap:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://ota-mariadb:3306/campaigner
  DB_USER: campaigner
  DEVICE_REGISTRY_HOST: ota-device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: ota-director
  DIRECTOR_PORT: '80'
  JAVA_OPTS: '-Xmx200m'
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  MESSAGING_MODE: kafka
  LOG_APPENDER: async_json
  REPORT_METRICS: "false"
  SCHEDULER_BATCH_SIZE: '200'
  SCHEDULER_DELAY: 10 seconds
  SCHEDULER_POLLING_TIMEOUT: 10 seconds
  USER_PROFILE_HOST: ota-user-profile
  USER_PROFILE_PORT: '80'
  ATS_HTTP_TRACING: "true"
  ZIPKIN_URI: "http://ota-zipkin:9411"

service:
  type: ClusterIP
  port: 80

secret:
  DB_PASSWORD: campaigner

ingress:
  enabled: true
  hosts:
    - campaigner.ota.local
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: []
  path: /

resources:
  requests:
    cpu: 80m
    memory: 250Mi

daemonResources:
  requests:
    cpu: 80m
    memory: 250Mi

prometheus:
  scrape: false

registryPullSecret: docker-registry-key

nodeSelector: {}

tolerations: []

affinity: {}

pdb:
  enabled: false
  maxUnavailable:
  minAvailable:
