replicaCount: 1
image:
  init_image: hcr.data.here.com/ota_saas/busybox:1.28.0
  repository: hcr.data.here.com/ota_saas/tuf-reposerver
  tag: latest
  pullPolicy: IfNotPresent

configMap:
  AKKA_HTTP_HOST_CONNECTION_POOL_IDLE_TIMEOUT: "30 s"
  AKKA_HTTP_SERVER_IDLE_TIMEOUT: "60 s"
  BIND_PORT: '9001'
  BIND_HOST: '0.0.0.0'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://ota-mariadb:3306/tuf_reposerver
  DB_USER: tuf_reposerver
  JAVA_OPTS: '-XshowSettings:vm -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2'
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  LOG_APPENDER: async_json
  REPORT_METRICS: "false"
  TUF_KEYSERVER_HOST: ota-tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_AWS_BUCKET_ID: ota-ce-tuf-reposerver
  TUF_REPOSERVER_AWS_REGION: eu-central-1
  TUF_REPOSERVER_SIZE_LIMIT: "536870912"
  TUF_REPOSERVER_UPLOAD_REQUEST_TIMEOUT: "20 s"
  LOCAL_STORAGE_ROOT: /data/tuf-reposerver
  STORAGE_TYPE: local
  ATS_HTTP_TRACING: "true"
  ZIPKIN_URI: "http://ota-zipkin:9411"
  OUT_OF_BAND_SIZE_LIMIT: "3GB"

secret:
  DB_PASSWORD: tuf_reposerver
  TUF_REPOSERVER_AWS_ACCESS_KEY: AKIA01234567890ABCD
  TUF_REPOSERVER_AWS_SECRET_KEY: abcdefghijklmnopqrstuvwxyz1234567890ABCD

service:
  publicTufReposerverType: ClusterIP
  publicTufReposerverPort: 80
  internalTufReposerverType: ClusterIP
  internalTufReposerverPort: 80
  # api-gateway config for SIT/PRD
  apiGateway:
    enabled: true
    podPort: 8080
    selector:
      app: ota-api-gateway
  elbConnectionIdleTimeout: 120
  # These can be set when using the LoadBalancer type on a non-local setup:
  # internal: true
  # sslCert: arn:aws:iam::123456787890:server-certificate/cert-name
  # sslPorts: "*"
  # dnsName: tuf-reposerver.ota.local

ingress:
  enabled: true
  internalIngressEnabled: false
  hosts:
    - tuf-reposerver.ota.local
  serviceName: ota-tuf-reposerver
  internalHosts:
    - tuf-reposerver.ota.local
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: []

resources:
  limits:
    cpu: 1
    memory: 1.1Gi
  requests:
    cpu: 800m
    memory: 1Gi

persistence:
  enabled: true
  createVolumes: true
  hostPath: "/data/tuf-reposerver"
  accessMode: ReadWriteOnce
  size: 10Gi
  awsEnabled: false

# go through the API gateway
servicenameOverride: ota-api-gateway

deployPublic: true

pdb:
  enabled: false
  maxUnavailable:
  minAvailable:

prometheus:
  scrape: "true"
  port: 9001

registryPullSecret: docker-registry-key
