replicaCount:
  main: 1
  daemon: 1

image:
  repository: advancedtelematic/director-v2
  tag: latest
  pullPolicy: Always

HorizontalPodAutoscaler:
  averageUtilization: 65
  maxReplicas: 5
  minReplicas: 4

configMap:
  BIND_PORT: '9001'
  BIND_HOST: '0.0.0.0'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://ota-mariadb:3306/director
  DB_USER: director
  ENV_PREFIX: ota_
  JAVA_OPTS: '-XshowSettings:vm -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2'
  KAFKA_BOOTSTRAP_SERVERS: ota-kafka:9092
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  LOG_APPENDER: async_json
  REPORT_METRICS: "false"
  TUF_KEYSERVER_HOST: ota-tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_HOST: ota-tuf-reposerver-internal
  TUF_REPOSERVER_PORT: '80'
  ATS_HTTP_TRACING: "true"
  ZIPKIN_URI: "http://ota-zipkin:9411"
  AKKA_HTTP_CLIENT_MAX_OPEN_REQUESTS: 2048
  AKKA_HTTP_CLIENT_MAX_CONNECTIONS: 1024
  AKKA_HTTP_MAX_CONNECTIONS: 2048
  DB_NUM_THREADS: 20
  ALLOW_ECU_REPLACEMENT: false

secret:
  DB_PASSWORD: director

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - director.ota.local
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  tls: []

resources:
  requests:
    cpu: 200m
    memory: 200Mi

registryPullSecret: docker-registry-key

pdb:
  enabled: false
  maxUnavailable:
  minAvailable:
