---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  AUTH_PROTOCOL: none
  AUTH_VERIFICATION: local
  BIND_HOST: 0.0.0.1
  BIND_PORT: '9001'
  CAMPAIGNER_HOST: campaigner
  CAMPAIGNER_PORT: '80'
  CRYPT_CREATE_ACCOUNTS: "false"
  DEVICE_GATEWAY_PORT: '8000'
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: director
  DIRECTOR_PORT: '80'
  ENV_PREFIX: {{ .envPrefix }}
  EXTRA_CONNECT_SRC: "ws://web-events.{{ .externalDomain }}:80"
  JAVA_OPTS: {{ .javaOpts }}
  KAFKA_HOST: {{ .kafkaHost }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafkaTopicPrefix }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafkaHost }}:9092
  MESSAGING_MODE: kafka
  OIDC_LOGIN_ACTION: com.advancedtelematic.auth.garage.NoLoginAction
  OIDC_NS_PROVIDER: com.advancedtelematic.auth.oidc.ConfiguredNamespace
  OIDC_TOKEN_EXCHANGE: com.advancedtelematic.auth.NoExchange
  OIDC_TOKEN_VERIFICATION: com.advancedtelematic.auth.oidc.TokenValidityCheck
  PACKAGES_VERSION_FORMAT: ".+"
  PLAY_HTTP_SESSION_SECURE: 'false'
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TOGGLE_ATS_GARAGE_THEME: "false"
  TOGGLE_AUTO_FEATURE_ACTIVATION: "false"
  TOGGLE_CREDENTIALS_DOWNLOAD: "false"
  TOGGLE_PREBUILT_DEBRPM: "false"
  TOGGLE_USER_PROFILE_MENU: "false"
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
  WS_HOST: web-events.{{ .externalDomain }}
  WS_PORT: '80'
  WS_SCHEME: ws
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: {{ .appImage }}
        name: app
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: app0
        args:
        - "-Dhttp.port=9001"
        - "-Dwebsrc.atsgarage=ws://*.atsgarage.com:80"
        resources:
          requests:
            cpu: {{ .appCpu }}
            memory: {{ .appMemory }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app.{{ .externalDomain }}
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  JWT_SECRET: {{ .appJwtSecret | b64enc }}
  PLAY_CRYPTO_SECRET: {{ .appPlayCryptoSecret | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: app0
  selector:
    app: app
