---
apiVersion: v1
kind: ConfigMap
metadata:
  name: campaigner-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysqlHost }}:3306/campaigner
  DB_USER: campaigner
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: director
  DIRECTOR_PORT: '80'
  ENV_PREFIX: {{ .envPrefix }}
  JAVA_OPTS: {{ .javaOpts }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafkaHost }}:9092
  KAFKA_HOST: {{ .kafkaHost }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafkaTopicPrefix }}
  MESSAGING_MODE: kafka
  REPORT_METRICS: "false"
  SCHEDULER_BATCH_SIZE: '200'
  SCHEDULER_DELAY: 10 seconds
  SCHEDULER_POLLING_TIMEOUT: 10 seconds
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: campaigner
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: campaigner
    spec:
      containers:
      - image: {{ .campaignerImage }}
        name: campaigner
        envFrom:
        - configMapRef:
            name: campaigner-config
        - secretRef:
            name: campaigner-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: campaigner0
        args:
        resources:
          requests:
            cpu: {{ .campaignerCpu }}
            memory: {{ .campaignerMemory }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: campaigner
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: campaigner.{{ .externalDomain }}
    http:
      paths:
      - backend:
          serviceName: campaigner
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: campaigner-secret
type: Opaque
data:
  DB_PASSWORD: {{ .campaignerDbPassword | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: campaigner
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: campaigner0
  selector:
    app: campaigner
