---
apiVersion: v1
kind: ConfigMap
metadata:
  name: director-daemon-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysqlHost }}:3306/director
  DB_USER: director
  ENV_PREFIX: {{ .envPrefix }}
  JAVA_OPTS: {{ .javaOpts }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafkaHost }}:9092
  KAFKA_HOST: {{ .kafkaHost }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafkaTopicPrefix }}
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TUF_KEYSERVER_HOST: tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: director-daemon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: director-daemon
    spec:
      containers:
      - image: {{ .directorImage }}
        name: director-daemon
        envFrom:
        - configMapRef:
            name: director-daemon-config
        - secretRef:
            name: director-daemon-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: dir-daem0
        args:
        - "-main"
        - com.advancedtelematic.director.daemon.DaemonBoot
        resources:
          requests:
            cpu: {{ .directorDaemonCpu }}
            memory: {{ .directorDaemonMemory }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: director-daemon
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: director-daemon.{{ .externalDomain }}
    http:
      paths:
      - backend:
          serviceName: director-daemon
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: director-daemon-secret
type: Opaque
data:
  DB_PASSWORD: {{ .directorDbPassword | b64enc }}
