---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  JAVA_OPTS: {{ .javaOpts }}
  KAFKA_ADVERTISED_HOST_NAME: {{ .kafkaHost }}
  KAFKA_ADVERTISED_PORT: "9092"
  KAFKA_BROKER_ID: "0"
  KAFKA_PORT: "9092"
  KAFKA_ZOOKEEPER_CONNECT: {{ .zookeeperHost }}:2181
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: {{ .kafkaImage }}
        name: kafka
        envFrom:
        - configMapRef:
            name: kafka-config
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ .kafkaCpu }}
            memory: {{ .kafkaMemory }}
        ports:
        - containerPort: 9092
          name: kafka
        volumeMounts:
        - name: kafka-persistent-storage
          mountPath: /var/lib/kafka
      volumes:
        - name: kafka-persistent-storage
          persistentVolumeClaim:
            claimName: kafka-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kafka-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  labels:
    app: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka
