---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-events-config
data:
  AUTH_PROTOCOL: none
  AUTH_VERIFICATION: local
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  ENV_PREFIX: {{ .envPrefix }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafkaHost }}:9092
  KAFKA_HOST: {{ .kafkaHost }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafkaTopicPrefix }}
  PACKAGES_VERSION_FORMAT: ".+"
  REPORT_METRICS: "false"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-events
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-events
    spec:
      containers:
      - image: {{ .webEventsImage }}
        name: web-events
        envFrom:
        - configMapRef:
            name: web-events-config
        - secretRef:
            name: web-events-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: web-events0
        args:
        resources:
          requests:
            cpu: {{ .webEventsCpu }}
            memory: {{ .webEventsMemory }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-events
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: web-events.{{ .externalDomain }}
    http:
      paths:
      - backend:
          serviceName: web-events
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: web-events-secret
type: Opaque
data:
  JWT_SECRET: {{ .webEventsJwtSecret | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-events
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: web-events0
  selector:
    app: web-events
