---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data:
  JAVA_OPTS: {{ .javaOpts }}
  ZOOKEEPER_ID: "1"
  ZOOKEEPER_SERVER_1: zookeeper
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: {{ .zookeeperImage }}
        name: zookeeper
        envFrom:
        - configMapRef:
            name: zookeeper-config
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
          name: zookeeper
        resources:
          requests:
            cpu: {{ .zookeeperCpu }}
            memory: {{ .zookeeperMemory }}
        volumeMounts:
        - name: zookeeper-persistent-storage
          mountPath: /var/lib/zookeeper
      volumes:
        - name: zookeeper-persistent-storage
          persistentVolumeClaim:
            claimName: zookeeper-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/zookeeper-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pv-claim
  labels:
    app: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper
