---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data:
  zookeeper.properties: |
    tickTime=2000
    dataDir=/var/lib/zookeeper/data
    dataLogDir=/var/lib/zookeeper/log
    clientPort=2181
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: {{ .zookeeperImage }}
        command:
          - /usr/share/apache-kafka/bin/zookeeper-server-start.sh
          - /usr/share/apache-kafka/config/zookeeper.properties
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: peer
        - containerPort: 3888
          name: election
        resources:
          requests:
            cpu: {{ .zookeeperCpu }}
            memory: {{ .zookeeperMemory }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/apache-kafka/config/zookeeper.properties
          subPath: zookeeper.properties
        - name: data
          mountPath: /var/lib/zookeeper
      volumes:
      - name: config
        configMap:
          name: zookeeper-config
          items:
          - key: zookeeper.properties
            path: zookeeper.properties
      - name: data
        persistentVolumeClaim:
          claimName: zookeeper-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/zookeeper-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pv-claim
  labels:
    app: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: peer
  - port: 3888
    name: election
  selector:
    app: zookeeper
