replicaCount: 1

image:
  repository: hcr.data.here.com/ota_saas/treehub
  tag: latest
  pullPolicy: IfNotPresent

lifecycle:
  preStopTimeSec: 15
  terminationGracePeriodSeconds: 30 # 30 sec is used by default

HorizontalPodAutoscaler:
  averageUtilization: 65
  maxReplicas: 3
  minReplicas: 2

readinessProbe:
  initialDelaySeconds: 20

configMap:
  AKKA_HTTP_MAX_CONTENT_LENGTH: "3GB"
  AKKA_HTTP_REQUEST_TIMEOUT: "2 minutes"
  AKKA_HTTP_IDLE_TIMEOUT: "2 minutes"
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://ota-mariadb:3306/treehub
  DB_USER: treehub
  DEVICE_REGISTRY_HOST: ota-device-registry
  DEVICE_REGISTRY_PORT: '80'
  JAVA_OPTS: '-XshowSettings:vm -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2'
  KAFKA_BOOTSTRAP_SERVERS: ota-kafka:9092
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  LOG_APPENDER: async_json
  MESSAGING_MODE: kafka
  TREEHUB_AWS_BUCKET_ID: some_aws_bucket
  DELTAS_AWS_BUCKET_ID: some_aws_bucket
  TREEHUB_AWS_REGION: eu-central-1
  TREEHUB_HOSTNAME: http://treehub.ota.local/api/v2/mydevice
  TREEHUB_LOCAL_STORE_PATH: "/treehub-objects"
  TREEHUB_STORAGE: local
  REPORT_METRICS: "false"
  INFLUXDB_HOST: influxdb
  INFLUXDB_PORT: "8086"
  ATS_HTTP_TRACING: "true"
  ZIPKIN_URI: "http://ota-zipkin:9411"

service:
  publicTreehubType: ClusterIP
  publicTreehubPort: 80
  internalTreehubType: ClusterIP
  internalTreehubPort: 80
  # api-gateway config for SIT/PRD
  apiGateway:
    enabled: true
    podPort: 8080
    selector:
      app: ota-api-gateway
  # These can be set when using the LoadBalancer type on a non-local setup:
  # internal: true
  # sslCert: arn:aws:iam::123456787890:server-certificate/cert-name
  # sslPorts: "*"
  # dnsName: treehub.ota.local

secret:
  DB_PASSWORD: treehub
  TREEHUB_AWS_ACCESS_KEY: AKIA01234567890ABCD
  TREEHUB_AWS_SECRET_KEY: abcdefghijklmnopqrstuvwxyz1234567890ABCD
  # AUTHPLUS_CLIENT_ID: authPlusTreehubId
  # AUTHPLUS_CLIENT_SECRET: authPlusTreehubSecret

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 3072m
  path: /
  hosts:
    - treehub.ota.local
  tls: []

resources:
  requests:
    cpu: 80m
    memory: 250Mi

prometheus:
  scrape: false

registryPullSecret: docker-registry-key

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  createVolumes: true
  hostPath: "/data/treehub"
  accessMode: ReadWriteOnce
  size: 10Gi
  awsEnabled: false

# go through the API gateway
servicenameOverride: ota-api-gateway

# PodDisruptionBudget. You can specify either maxUnavailable or minAvailable number of replicas
pdb:
  enabled: false
  maxUnavailable:
  minAvailable:
