---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ota-device-registry.fullname" . }}-daemon
  labels:
    app: {{ template "ota-device-registry.name" . }}-daemon
    chart: {{ template "ota-device-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.daemon }}
  selector:
    matchLabels:
      app: {{ template "ota-device-registry.name" . }}-daemon
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ota-device-registry.name" . }}-daemon
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- if .Values.registryPullSecret }}
      imagePullSecrets:
      - name: {{ .Values.registryPullSecret }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-daemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ template "ota-device-registry.fullname" . }}
          - secretRef:
              name: {{ template "ota-device-registry.fullname" . }}
          ports:
            - containerPort: {{ .Values.configMap.BIND_PORT }}
              name: http
          args:
            - "-main"
            - com.advancedtelematic.ota.deviceregistry.DaemonBoot
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 30
            httpGet:
              path: /health
              port: {{ .Values.configMap.BIND_PORT }}
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: 10
            httpGet:
              path: /health
              port: {{ .Values.configMap.BIND_PORT }}
          resources:
{{ toYaml .Values.daemonResources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
