#!/bin/sh -e

GCLOUD_CONFIG="${GCLOUD_CONFIG-`pwd`/gcloud-config}"
if [ ! -e $GCLOUD_CONFIG ] ; then
	echo "Creating gcloud config on host at: $GCLOUD_CONFIG"
	sudo mkdir $GCLOUD_CONFIG
	sudo mkdir $GCLOUD_CONFIG/kube-config
fi


if [ "$1" = "shell" ] ; then
	exec docker run --rm ${EXTRA_ARGS} -v ${GCLOUD_CONFIG}:/root/.config/gcloud otace-client /bin/sh
fi
exec docker run --rm ${EXTRA_ARGS} -v ${GCLOUD_CONFIG}:/root/.config/gcloud otace-client gcloud $*
