#!/bin/sh -e

# Find our way to the source root
cd $(dirname $(readlink -f $0))
cd ../../

GCLOUD_CONFIG="${GCLOUD_CONFIG-`pwd`/gcloud-config}"

docker run --rm -v ${GCLOUD_CONFIG}:/root/.config/gcloud -v `pwd`:/src otace-client \
	make -C /src $*
